module.exports = {
  apps: [
    {
      name: "agentic-api-v3",
      script: "api/v3/dashboard_api_v3.py",
      interpreter: "python3",
      cwd: ".",
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 5000,
      env: { API_PORT: "5004" },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "agentic-download-server",
      script: "shared/core/download_server.py",
      interpreter: "python3",
      cwd: ".",
      instances: 1,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 3000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "agentic-media-server",
      script: "shared/core/media_server.py",
      interpreter: "python3",
      cwd: ".",
      instances: 1,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 3000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "agentic-decision-poller",
      script: "shared/core/decision_poller.py",
      interpreter: "python3",
      cwd: ".",
      instances: 1,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "agentic-mcp-bridge",
      script: "shared/mcp_task_server.py",
      interpreter: "python3",
      cwd: ".",
      instances: 1,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 3000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "agentic-vue-spa",
      script: "npm",
      args: "run dev",
      cwd: "web",
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "agentic-daily-summary",
      script: "tk/openclaw/core/daily_business_summary.py",
      interpreter: "python3",
      cwd: ".",
      instances: 1,
      autorestart: false,
      cron_restart: "0 10 * * *",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
